service: vaccinate-texas
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.7
  timeout: 60
  profile: default
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: '*'
    - Effect: "Allow"
      Action:
        - secretsmanager:*
      Resource: '*'
    
functions:
  fetch_tdem: 
    handler: fetch_tdem.main
    layers:
      - arn:aws:lambda:us-east-1:359698300326:layer:vtx-sls-layer:1
    events: 
      - schedule: 
          rate: rate(1 hour)
  fetch_heb: 
    handler: fetch_heb.main
    layers:
      - arn:aws:lambda:us-east-1:359698300326:layer:vtx-sls-layer:1
    events: 
      - schedule: 
          rate: rate(10 minutes)
  push_heb_notification: 
    handler: push_heb_notification.main
    layers:
      - arn:aws:lambda:us-east-1:359698300326:layer:vtx-sls-layer:1
    events: 
      - schedule: 
          rate: rate(10 minutes)
  
