service: vtx-heb
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.7
  timeout: 60
  profile: default
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: '*'
    - Effect: "Allow"
      Action:
        - secretsmanager:*
      Resource: '*'
    
functions:
  fetch_and_push_heb: 
    handler: handler.main
    layers:
      - arn:aws:lambda:us-east-1:359698300326:layer:vtx-sls-layer:1
    events: 
      - schedule: 
          rate: rate(5 minutes)
  
