service: vtx-subscriptions
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.7
  profile: default
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: '*'
    - Effect: "Allow"
      Action:
        - secretsmanager:*
      Resource: '*'
    
functions:
  inbound_sms_handler: 
    handler: handler.main
    events:
      - httpApi:
          path: /sms/inbound
          method: post
    layers:
      - arn:aws:lambda:us-east-1:359698300326:layer:vtx-sls-layer:1